package com.wot.helper.domain.models.models.profileinfo

data class Team(
    val avg_damage_assisted: Double? = null,
    val avg_damage_assisted_radio: Double? = null,
    val avg_damage_assisted_track: Double? = null,
    val avg_damage_blocked: Double? = null,
    val battle_avg_xp: Int? = null,
    val battles: Int? = null,
    val battles_on_stunning_vehicles: Int? = null,
    val capture_points: Int? = null,
    val damage_dealt: Int? = null,
    val damage_received: Int? = null,
    val direct_hits_received: Int? = null,
    val draws: Int? = null,
    val dropped_capture_points: Int? = null,
    val explosion_hits: Int? = null,
    val explosion_hits_received: Int? = null,
    val frags: Int? = null,
    val hits: Int? = null,
    val hits_percents: Int? = null,
    val losses: Int? = null,
    val max_damage: Int? = null,
    val max_damage_tank_id: Any? = null,
    val max_frags: Int? = null,
    val max_frags_tank_id: Any? = null,
    val max_xp: Int? = null,
    val max_xp_tank_id: Any? = null,
    val no_damage_direct_hits_received: Int? = null,
    val piercings: Int? = null,
    val piercings_received: Int? = null,
    val shots: Int? = null,
    val spotted: Int? = null,
    val stun_assisted_damage: Int? = null,
    val stun_number: Int? = null,
    val survived_battles: Int? = null,
    val tanking_factor: Double? = null,
    val wins: Int? = null,
    val xp: Int? = null
)