package com.wot.helper.domain.models.models.tanksinfo

data class TankInfo(
    val description: String? = null,
    val engines: ArrayList<Int>? = null,
    val guns: ArrayList<Int>? = null,
    val is_gift: Boolean? = null,
    val is_premium: Boolean? = null,
    val is_premium_igr: Boolean? = null,
    val is_wheeled: Boolean? = null,
    val name: String? = null,
    val nation: String? = null,
    val next_tanks: HashMap<Int,Int>,
    val price_credit: Int? = null,
    val price_gold: Int? = null,
    val prices_xp: HashMap<Int,Int>? = null,
    val provisions: ArrayList<Int>? = null,
    val radios: ArrayList<Int>? = null,
    val short_name: String? = null,
    val suspensions: ArrayList<Int>? = null,
    val tag: String? = null,
    val tank_id: Int? = null,
    val tier: Int? = null,
    val turrets: ArrayList<Int>? = null,
    val type: String? = null,
    val crew: ArrayList<Crew>? = null,
    val default_profile: DefaultProfile? = null,
    val images: Images? = null,
    val modules_tree: ModulesTree? = null,
    val multination: Multination? = null,
)